/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
//const sidebars = {
// By default, Docusaurus generates a sidebar from the docs folder structure
// mainSidebar: [{type: 'autogenerated', dirName: '.'}],

// But you can create a sidebar manually


module.exports = {
  docs: [
    {
      type: 'doc',
      label: 'API Guide',
      id: 'intro'
    },
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'generated-index'
      },
      // collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'overview/auth'
        },
        {
          type: 'doc',
          id: 'overview/sendrequest'
        },
      ]
    },
    {
      type: 'category',
      label: 'Working with the API',
      link: {
        type: 'generated-index'
      },
      items: [
        {
          type: 'doc',
          id: 'howitworks/errors'
        },
        {
          type: 'doc',
          id: 'howitworks/commontasks'
        },
      ]
    },
    {
      type: 'category',
      label: 'API specification',
      link: {
        type: 'generated-index'
      },
      items: [
        {
          type: 'doc',
          id: 'howitworks/workwithspec'
        },
        {
          type: 'link',
          label: 'Nmbrs API specification',
          href: 'https://documenter.getpostman.com/view/18344436/2sA3XLDijZ',
        },
      ]
    },
    /*
    {
      type: 'doc',
      label: 'API Specification Links',
      id: 'apiguide',
    },

   {
     type: 'category',
     label: 'Network Access Control',
     items: [
       {
         type: 'doc',
         id: 'nac/nacoverview',
         label: 'NAC Overview'
       },
       {
         type: 'doc',
         id: 'nac/nacconfig',
         label: 'NAC Setup Guide'
       },
       {
         type: 'doc',
         id: 'nac/arcmonitor',
         label: 'ARC monitoring'
       },
     ]
   },
   {
     type: 'category',
     label: 'Rule Lists',
     items: [
       {
         type: 'doc',
         id: 'rulelists/rulelistsoverview',
         label: 'Rule Lists Overview'
       },
       {
         type: 'doc',
         id: 'rulelists/rulelistsconfig',
         label: 'Rule Lists Configuration Guide'
       },
     ]
   },
   */

  ],
};



